loop:
  timePerTick: 50
  allowMaxTick: 200
  allowWaitTime: 500
  playerNumber: 2

map:
  height: 500
  width: 500
  maxAllowPlayer: 2
  birthPlaces:
    '1':
      x: 75
      y: 75
    '2':
      x: 425
      y: 425

carrier:
  normal:
    health: 2000
    speed: 0.1
    radius: 30
    healRate: 0
    healPower: 0
    sightAngle: 0.6
    longSight: 100
    shortSight: 50
  weapon:
    radius: 10
    damage: 60
    speed: 5
    cd: 100
  nuke:
    aoeDamage: 2000
    aoeRadius: 100
    damageDecrease: 20
    radius: 50
    speed: 5

bomber:
  normal:
    health: 500
    speed: 0.5
    radius: 10
    healRate: 1
    healPower: 20
    sightAngle: 0.4
    longSight: 120
    shortSight: 80
  weapon:
    radius: 10
    damage: 80
    speed: 10
    cd: 50

fighter:
  normal:
    health: 200
    speed: 5
    radius: 10
    healRate: 5
    healPower: 5
    sightAngle: 0.2
    longSight: 70
    shortSight: 60
  weapon:
    radius: 2
    damage: 20
    speed: 20
    cd: 10
  rebuild:
    tick: 200
    power: 100

largeStar:
  power: 40
  radius: 5
  collectTick: 20

littleStar:
  power: 20
  radius: 3
  collectTick: 10

